/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demonized_ndktest_WelcomeActivity */

#ifndef _Included_com_demonized_ndktest_WelcomeActivity
#define _Included_com_demonized_ndktest_WelcomeActivity
#endif
